server:
  port: 9090

spring:
  aop:
    auto: true
    proxy-target-class: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    ##时间戳统一转换
    date-format: yyyy-MM-dd HH:mm:ss

# Zookeeper组件配置
curator:
  retryCount: 5
  elapsedTimeMs: 5000
  connectString: 192.168.0.1:2181
  # session超时时间
  sessionTimeoutMs: 60000
  # 连接超时时间
  connectionTimeoutMs: 5000