server:
  port: 9090
spring:
  aop:
    auto: true
    proxy-target-class: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    ##时间戳统一转换
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      ##配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 2000
      ## 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000
      remove-abandoned: true
      remove-abandoned-timeout: 180
      log-abandoned: false
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      keep-alive: true
      phy-timeout-millis: 500
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=6000
  application:
    name: nova-app

es:
  host: 192.168.147.132
  port: 9200
  scheme: http

# mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml