server:
  port: 8082
  servlet:
    context-path: /auto

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.147.132:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    #oracle配置
#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.10.10:1521:helowin
#    username: weathertop
#    password: 123456
    #SQLServer配置
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_security
#    username: weathertop
#    password: 123456
    #PostgreSQL配置
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.10.10:5432/renren_security
#    username: weathertop
#    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/


mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
weathertop:
  database: mysql